# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk:
- openjdk12

services:
- postgresql

before_install:
-  psql -c 'create database tracker;' -U postgres
-  psql -c 'create database db_134839;' -U postgres


# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту gasevskyv@gmail.com если сборка упала
notifications:
  email:
    recipients:
    - gasevskyv@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
  - CODECOV_TOKEN="8ebf84bd-ab26-4130-b346-f199aecd27fd"



