CREATE TABLE if NOT EXISTS student (
	id SERIAL PRIMARY KEY NOT NULL,
	firstName VARCHAR (50) NOT NULL,
	surName VARCHAR (50) NOT NULL,
	faculty VARCHAR (50) NOT NULL,
	edGroup VARCHAR (50) NOT NULL
);